"""
Converts sklearn DecisionTree to Rust constants.
Output: inference/src/weights.rs
This file is the bridge between Python ML and Rust PVM.
"""
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import joblib
from pathlib import Path


def export_to_rust(
    model: DecisionTreeClassifier,
    feature_names: list,
    ecosystem_avg: float,
):
    """
    Extracts feature importances and thresholds from decision tree.
    Converts to integer weights scaled to sum ~1000 (basis points).
    Writes inference/src/weights.rs.
    """
    importances = model.feature_importances_

    # Scale to integers (sum to ~1000)
    weights = (importances * 1000).astype(int)

    lines = [
        "// AUTO-GENERATED by ml/export_weights.py — DO NOT EDIT MANUALLY",
        "// Retrain model and re-run export_weights.py to update",
        "",
        "/// Feature weights scaled to sum ~1000 (basis points).",
        "/// Index matches FEATURE order in FenrirInference::score_proposal().",
        "#[allow(dead_code)]",
        f"pub const FEATURE_WEIGHTS: [i32; {len(weights)}] = [",
    ]

    for i, (name, w) in enumerate(zip(feature_names, weights)):
        lines.append(f"    {w},  // [{i}] {name}")

    lines.extend([
        "];",
        "",
        "/// Ecosystem average DOT request (in Planck, 1e18 units).",
        f"pub const ECOSYSTEM_AVG_DOT: u64 = {int(ecosystem_avg * 1e18)};",
        "",
        "/// Thresholds for flag generation",
        "pub const WALLET_AGE_THRESHOLD_BLOCKS: u64 = 50_000;",
        "pub const DOT_RATIO_HIGH_RISK: u64 = 300;        // 3x average = 300%",
        "pub const MIN_APPROVAL_RATE: u64 = 20;           // below 20% is suspect",
        "pub const BURST_WINDOW_BLOCKS: u64 = 7_200;      // ~12 hours",
    ])

    output = Path("../inference/src/weights.rs")
    output.write_text("\n".join(lines))
    print(f"Weights exported to {output}")
    print(f"Feature importances: {dict(zip(feature_names, weights))}")


if __name__ == "__main__":
    model = joblib.load("model.joblib")
    feature_names = [
        "wallet_age_blocks", "requested_dot", "dot_ratio_to_avg",
        "prior_approved", "prior_total", "approval_rate",
        "track_id", "days_since_last_prop",
    ]
    export_to_rust(model, feature_names, ecosystem_avg=5000.0)
