"""
Converts sklearn DecisionTree to Rust constants.
Output: inference/src/weights.rs
This file is the bridge between Python ML and Rust PVM.
"""
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import joblib
from pathlib import Path


def export_to_rust(
    model: DecisionTreeClassifier,
    feature_names: list,
    ecosystem_avg: float,
):
    """
    Extracts feature importances from decision tree and writes Rust constants.

    Output layout is fixed to match the consumption order in lib.rs:
      [0] wallet_age_blocks  — Feature 1: wallet age risk
      [1] dot_ratio_to_avg   — Feature 2: DOT request ratio risk
      [2] approval_rate      — Feature 3: approval history risk
      [3..] remaining features (unused by current Rust logic)

    Domain-knowledge minimum floors are applied so that all three active
    features contribute to the score even when the training set is small
    and the model collapses onto a single discriminating feature.
    """
    importances = model.feature_importances_
    idx = {name: i for i, name in enumerate(feature_names)}

    # Pull raw importances for the three features lib.rs actually uses
    raw_wallet  = float(importances[idx["wallet_age_blocks"]])
    raw_dotratio= float(importances[idx["dot_ratio_to_avg"]])
    raw_approval= float(importances[idx["approval_rate"]])

    # Domain-knowledge minimums (basis points out of 1000):
    # Even if the small training corpus doesn't surface these features,
    # wallet age, DOT ratio, and approval history are known risk signals.
    MIN_WALLET   = 0.20   # ≥ 20% contribution
    MIN_DOTRATIO = 0.15   # ≥ 15% contribution
    MIN_APPROVAL = 0.40   # ≥ 40% contribution

    w_wallet   = max(raw_wallet,   MIN_WALLET)
    w_dotratio = max(raw_dotratio, MIN_DOTRATIO)
    w_approval = max(raw_approval, MIN_APPROVAL)

    # Normalise the three active weights so they sum to exactly 1.0,
    # then scale to basis points (out of 1000).
    total = w_wallet + w_dotratio + w_approval
    bps_wallet   = int(round(w_wallet   / total * 1000))
    bps_dotratio = int(round(w_dotratio / total * 1000))
    bps_approval = 1000 - bps_wallet - bps_dotratio  # absorb rounding remainder

    # Remaining features (not consumed as weights by lib.rs — kept as 0)
    remaining_names = [n for n in feature_names
                       if n not in ("wallet_age_blocks", "dot_ratio_to_avg", "approval_rate")]

    # Final ordered layout expected by lib.rs
    ordered = [
        (bps_wallet,   "wallet_age_blocks  — wallet age risk weight"),
        (bps_dotratio, "dot_ratio_to_avg   — DOT ratio risk weight"),
        (bps_approval, "approval_rate      — approval history risk weight"),
    ] + [(0, f"{n}  — unused by scoring logic") for n in remaining_names]

    print(f"Active weights → wallet_age:{bps_wallet}  dot_ratio:{bps_dotratio}  approval:{bps_approval}")

    lines = [
        "// AUTO-GENERATED by ml/export_weights.py — DO NOT EDIT MANUALLY",
        "// Retrain model and re-run export_weights.py to update",
        "",
        "/// Feature weights in basis points (sum of active weights = 1000).",
        "/// Layout is fixed to match lib.rs consumption order:",
        "///   [0] wallet_age_blocks weight  (Feature 1)",
        "///   [1] dot_ratio_to_avg weight   (Feature 2)",
        "///   [2] approval_rate weight      (Feature 3)",
        "///   [3+] unused — kept for future features",
        "#[allow(dead_code)]",
        f"pub const FEATURE_WEIGHTS: [i32; {len(ordered)}] = [",
    ]

    for i, (w, name) in enumerate(ordered):
        lines.append(f"    {w},  // [{i}] {name}")

    lines.extend([
        "];",
        "",
        "/// Ecosystem average DOT request — stored in Planck units at 1e10 precision",
        "/// (1 DOT = 10^10 Planck in Polkadot). Values passed from FenrirScorer",
        "/// are also divided by 1e10 before the cross-VM call.",
        f"pub const ECOSYSTEM_AVG_DOT: u64 = {int(ecosystem_avg * 1e10)};  // {int(ecosystem_avg)} DOT",
        "",
        "/// Thresholds for flag generation",
        "pub const WALLET_AGE_THRESHOLD_BLOCKS: u64 = 50_000;",
        "pub const DOT_RATIO_HIGH_RISK: u64 = 300;        // 3x average = 300%",
        "pub const MIN_APPROVAL_RATE: u64 = 20;           // below 20% is suspect",
        "pub const BURST_WINDOW_BLOCKS: u64 = 7_200;      // ~12 hours",
    ])

    output = Path("../inference/src/weights.rs")
    output.write_text("\n".join(lines))
    print(f"Weights exported to {output}")


if __name__ == "__main__":
    model = joblib.load("model.joblib")
    feature_names = [
        "wallet_age_blocks", "dot_requested", "dot_ratio_to_avg",
        "prior_approved", "prior_total", "approval_rate",
        "track_id", "days_since_last_prop",
    ]
    export_to_rust(model, feature_names, ecosystem_avg=5000.0)
