// AUTO-GENERATED by ml/export_weights.py — DO NOT EDIT MANUALLY
// Retrain model and re-run export_weights.py to update

/// Feature weights scaled to sum ~1000 (basis points).
/// Index matches FEATURE order in FenrirInference::score_proposal().
///   [0] wallet_age_blocks
///   [1] requested_dot (ratio to ecosystem average)
///   [2] approval_history
#[allow(dead_code)]
pub const FEATURE_WEIGHTS: [i32; 3] = [
    350,  // [0] wallet_age_blocks
    300,  // [1] requested_dot ratio
    350,  // [2] approval_history
];

/// Ecosystem average DOT request (in Planck, 1e18 units).
/// Used as baseline for the DOT ratio calculation.
pub const ECOSYSTEM_AVG_DOT: u64 = 5_000_000_000_000_000_000_000; // 5000 DOT

/// Thresholds for flag generation
pub const WALLET_AGE_THRESHOLD_BLOCKS: u64 = 50_000;  // ~83 days at 6s/block
pub const DOT_RATIO_HIGH_RISK: u64 = 300;             // 3x average = 300%
pub const MIN_APPROVAL_RATE: u64 = 20;                // below 20% is suspect
pub const BURST_WINDOW_BLOCKS: u64 = 7_200;           // ~12 hours
