// AUTO-GENERATED by ml/export_weights.py — DO NOT EDIT MANUALLY
// Retrain model and re-run export_weights.py to update

/// Feature weights in basis points (sum of active weights = 1000).
/// Layout is fixed to match lib.rs consumption order:
///   [0] wallet_age_blocks weight  (Feature 1)
///   [1] dot_ratio_to_avg weight   (Feature 2)
///   [2] approval_rate weight      (Feature 3)
///   [3+] unused — kept for future features
#[allow(dead_code)]
pub const FEATURE_WEIGHTS: [i32; 8] = [
    148,  // [0] wallet_age_blocks  — wallet age risk weight
    111,  // [1] dot_ratio_to_avg   — DOT ratio risk weight
    741,  // [2] approval_rate      — approval history risk weight
    0,  // [3] dot_requested  — unused by scoring logic
    0,  // [4] prior_approved  — unused by scoring logic
    0,  // [5] prior_total  — unused by scoring logic
    0,  // [6] track_id  — unused by scoring logic
    0,  // [7] days_since_last_prop  — unused by scoring logic
];

/// Ecosystem average DOT request — stored in Planck units at 1e10 precision
/// (1 DOT = 10^10 Planck in Polkadot). Values passed from FenrirScorer
/// are also divided by 1e10 before the cross-VM call.
pub const ECOSYSTEM_AVG_DOT: u64 = 100000000000000;  // 10000 DOT

/// Thresholds for flag generation
pub const WALLET_AGE_THRESHOLD_BLOCKS: u64 = 50_000;
pub const DOT_RATIO_HIGH_RISK: u64 = 300;        // 3x average = 300%
pub const MIN_APPROVAL_RATE: u64 = 20;           // below 20% is suspect
pub const BURST_WINDOW_BLOCKS: u64 = 7_200;      // ~12 hours